name: Maven Test Selenium CI

on:        # on: định nghĩa các event ích hoạt workflow
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  tests:     # đặt tên job là "tests" ( đặt tên nào cũng được)
    runs-on: ubuntu-latest   # chỉ định OS của sever github

    steps:
      - name:  Checkout code
        uses: action/checkout@v4    # action có sẵn của github giúp clone source code về
      - name: Setup JDK 21
        uses: actions/setup-java@v4

        with:
          distribution: temurin    # temurin là nhà cung cấp JDK Java
          java-vision: "21"
          cache: maven     # cache những dependency đã cài trước đó giúp chạy nhanh hơn ở những lần sau
      - name: Run maven tests
        run: mvn -B test
